---
title: "PAM_analysis"
author: "Caitlin Bergman"
date: "11/11/2021"
output: html_document
---

```{r}
#load libraries:
library(rstatix) #Used for anova_test function
library(DHARMa)
library(fitdistrplus)#Used to fit distributions to data
library(goft)
library(gamlss) # For gamlss models
library(ordinal)#For ordinal regression
library(performance)
library(tidyverse)

#Loading data
pam<-read_delim("data/pam_data.csv", delim = ",")
base <- read_delim("data/base_diameter_data.csv", delim = ",")
food <- read_delim("data/feeding_time_data.csv", delim = ",")
open_closed <- read_delim("data/open_closed_data.csv", delim = ",")
```

# Cleaning data

```{r}
#Function to calculate standard error for summarizing data
standard_error <- function(x) sd(x) / sqrt(length(x))
#PAM data
pam_clean <- pam %>%
  filter(Measurement != "NA")%>% #Removing dates with PAM measurements that we are not using due to technical errors
  select(Date,Time,Measurement,Treatment,Bin,Site,Anemone_ID,Fv_Fm_av)%>%
  mutate(Date = as.POSIXct(as.character(Date),
                           format="%m/%d/%Y %H:%M:%S"),
         Anemone_ID = as.factor(Anemone_ID), 
         Bin = as.factor(Bin), 
         Measurement = as.factor(Measurement), 
         Site = as.factor(Site), 
         Time = factor(Time, levels = c("Morning", "Afternoon")),
         Treatment = fct_relevel(as.factor(Treatment), "Control", "25C", "30C"))

pam_summary <- pam_clean%>%
  group_by(Date, Measurement, Treatment) %>%
  summarize(mean_FvFm = mean(Fv_Fm_av), se_FvFm = standard_error(Fv_Fm_av))

#Base data
base_clean<-base%>%
  filter(Treatment != "NA", Average_Diameter != "NA")%>% 
  mutate(Date = factor(Date, levels =c("Oct 31", "Nov 5", "Nov 9", "Nov 13")), Treatment = fct_relevel(as.factor(Treatment), "Control", "25C", "30C"), Anemone_ID = as.factor(Anemone_ID), Bin = as.factor(Bin), Site = as.factor(Site)) %>% 
select(Date,Treatment,Bin,Site,Anemone_ID,Average_Diameter)

base_summary <- base_clean%>%
  group_by(Date, Treatment)%>%
  summarize(mean_base = mean(Average_Diameter), se_base = standard_error(Average_Diameter))

#Feeding time data
food_clean <- food%>%
  filter(Date != "10/28/2021")%>%
  mutate(Feeding_Time_Min = as.numeric(Feeding_Time_Min),Date = as.factor(Date), Site = as.factor(Site), Treatment = as.factor(Treatment), Anemone_ID = as.factor(Anemone_ID), Bin = as.factor(Bin))%>%
select(Date, Treatment, Bin, Site, Anemone_ID, Feeding_Time_Min)

food_summary <- food%>%
  group_by(Date, Treatment)%>%
  summarize(mean_time = mean(Feeding_Time_Min), se_time = standard_error(Feeding_Time_Min))

open_closed_clean <- open_closed %>%
  mutate(Date = as.factor(Date),Anemone_ID = as.factor(Anemone_ID),Time_Block = fct_relevel(as.factor(Time_Block), "0", "1", "2", "3", "4", "5", "6"), Treatment = as.factor(Treatment),  Open_Closed = as.factor(Open_Closed), Open_Closed = factor(Open_Closed, levels = c("Open", "Partially open", "Closed"), ordered = TRUE), Treatment = fct_relevel(Treatment, "Control", "25C", "30C"))%>%
  select(Date, Time_Block, Treatment, Open_Closed, Anemone_ID)

open_closed_summary <- open_closed_clean %>%
group_by(Date, Treatment, Time_Block)%>%
  count(Open_Closed)
```

# PAM data

## Plots

```{r}
#Line graph of all PAM data

ggplot(data = pam_summary, 
       aes(x=Date, 
           y = mean_FvFm, 
           group = Treatment, 
           colour = Treatment)) +
  theme_classic() +
  geom_vline(xintercept = as.POSIXct("2021-11-06 09:00:00"),
             linetype = "dotted", 
             size = 1) +
  geom_vline(xintercept = as.POSIXct("2021-11-08 16:00:00"), 
             linetype = "dotted", 
             size = 1)+
  geom_point(size=2.5) +
  geom_line(lwd = 1.5) +
  geom_errorbar(aes(ymin = mean_FvFm - se_FvFm, 
                    ymax = mean_FvFm + se_FvFm), 
                    width=30000)+
  labs(x="Date", 
       y = "Photosynthetic efficiency (Fv/Fm)") +
  scale_fill_manual(values = c('#89226AFF',
                              '#2C728EFF',    
                              '#E65154FF')) +
  scale_colour_manual(values = c('#89226AFF',
                                 '#2C728EFF',
                                 '#E65154FF'))+
  theme(axis.text=element_text(size=15),
        axis.title=element_text(size=20), 
        legend.text=element_text(size=15), 
        legend.title=element_text(size=20))

ggsave(path = "plots",filename = "pam_recovery_line.png", width = 10, height = 7)

#Graph of PAM data during heatwave, with heatwave time periods marked
ggplot(data = filter(pam_summary, 
                     Measurement != "T1" & Measurement != "T8" & Measurement != "T9"), 
                     aes(x=Date, 
                         y = mean_FvFm, 
                         group = Treatment, 
                         colour = Treatment)) +
theme_classic() +
geom_rect(xmin=as.POSIXct("2021-11-06 9:00:00"), 
          xmax=as.POSIXct("2021-11-06 15:00:00"), 
          ymin = 0.40, 
          ymax = 0.60, 
          fill = "grey84",
          colour = "grey84")+
geom_rect(xmin=as.POSIXct("2021-11-07 9:00:00"), 
          xmax=as.POSIXct("2021-11-07 15:00:00"), 
          ymin = 0.40, 
          ymax = 0.60, 
          fill = "grey84", 
          colour = "grey84")+
geom_rect(xmin=as.POSIXct("2021-11-08 9:00:00"), 
          xmax=as.POSIXct("2021-11-08 15:00:00"), 
          ymin = 0.40, 
          ymax = 0.60,
          fill = "grey84",
          colour = "grey84")+
geom_point() +
geom_line() +
geom_errorbar(aes(ymin = mean_FvFm - se_FvFm, 
                  ymax = mean_FvFm + se_FvFm), 
              width=10000)+
labs(x="Date", 
     y = "Photosynthetic efficiency (Fv/Fm)") +
scale_fill_manual(values = c('#89226AFF',
                             '#2C728EFF',           
                             '#E65154FF')) +
scale_colour_manual(values = c('#89226AFF', 
                               '#2C728EFF', 
                              '#E65154FF'))+
  theme(axis.text=element_text(size=15),
        axis.title=element_text(size=20), 
        legend.text=element_text(size=15), 
        legend.title=element_text(size=20))
ggsave(path = "plots",filename = "pam_heatwave_line.png", width = 10, height = 7)

#Boxplot of pam morning vs. afternoon data
pam_heatwave<-pam_clean%>%
  filter(Measurement == "T2" | 
        Measurement == "T3" | 
        Measurement == "T6" | 
        Measurement == "T7") %>%
  separate(Date, c('Day', 'Hour'), sep = " ", remove = T)

ggplot(pam_heatwave, aes(fill=Treatment, y=Fv_Fm_av, x=Time)) + 
  geom_boxplot() +
  scale_fill_manual(values = c('#89226AFF',
                             '#2C728EFF',           
                             '#E65154FF')) +
  theme(axis.text=element_text(size=15),
        axis.title=element_text(size=20), 
        legend.text=element_text(size=15), 
        legend.title=element_text(size=20)) +
  labs(x = "Time of day", y = "Photosynthetic efficiency (Fv/Fm)")+
  facet_grid(. ~ Day)
ggsave(path = "plots",filename = "pam_heatwave_boxplot.png")
```

## Testing distributions

```{r}
#Checking assumptions of PAM data
#Outliers
pam_clean %>%
  group_by(Measurement, Treatment) %>%
  identify_outliers(Fv_Fm_av)
#Test shows 15 outliers, and 4 extreme outliers

#Normality
pam_clean %>%
  group_by(Measurement, Treatment) %>%
  shapiro_test(Fv_Fm_av)
#10 time/treatment combinations that are not normally distributed  (P<0.05)

#Conclusion: Data does not meet assumptions of ANOVA. 

#Transformations (acrsin and log)
pam_clean <- pam_clean %>%
  mutate(arcsin_Fv_Fm = asin(sqrt(Fv_Fm_av)), log_Fv_Fm = log(Fv_Fm_av))

shapiro.test(pam_clean$arcsin_Fv_Fm)
shapiro.test(pam_clean$log_Fv_Fm)

#P-values for all transformations are less than 0.05. Data are still not normally distributed after transformation. 
```

```{r}
#Testing new distribution for PAM data

fitDist(Fv_Fm_av, data = pam_clean, type = "real0to1", try.gamlss = T)

#Generalized Beta 1 distribution is best fit

histDist(pam_clean$Fv_Fm_av, "GB1", density = F, main = "GB1")
```

## Gamlss model

```{r}
#Gamlss model for whole-experiment PAM data (T1, T2, T8, and T9) using Gumbel distribution:
pam_long_timeseries <- pam_clean %>% 
  filter(Measurement == "T1" | Measurement  == "T2" | Measurement == "T8" | Measurement == "T9")
         
fitDist(Fv_Fm_av, data = pam_long_timeseries, type = "realAll", try.gamlss = T)
#Outcome: Gumbel is the best fit

histDist(pam_long_timeseries$Fv_Fm_av, "GU", density = F, main = "Gumbel")

#Full model
pam_full_mod <- gamlss(Fv_Fm_av ~ Treatment + Measurement + Treatment*Measurement + random(Anemone_ID) + random(Site) + random(Bin), data = pam_long_timeseries, family = GU())

#Backwards model selection to find best model:
pam_mod <- stepGAIC(pam_full_mod, direction = "backward", trace = F)

formula(pam_mod)
#Final model includes treatment, measurement, treatment * measurement, and random(Anemone_ID)

summary(pam_mod)
```

```{r}
#Trying a gamlss model on PAM data (T2, T3, T6, T7), using GB1 distribution:
pam_short_timeseries <- pam_clean %>% 
  filter(Measurement == "T2" | Measurement  == "T3" |  Measurement == "T6" | Measurement == "T7")%>%
  mutate(Measurement = fct_relevel(Measurement, "T2", "T3", "T6", "T7"), Date = as.factor(Date))%>%
select(Date, Measurement, Treatment, Anemone_ID, Fv_Fm_av)


fitDist(Fv_Fm_av, data = pam_short_timeseries, type = "realAll", try.gamlss = T)
#Best fit: generalized beta type 1

histDist(pam_short_timeseries$Fv_Fm_av, "GB1", density = F, main = "generalised beta type 1")

# take out extra time point and retry
# if that doesn't work, could explore using GB1 distribution instead (fitDist with type = "real0to1"), mixed 50:100
pam_mod_full2 <- gamlss(Fv_Fm_av ~ Treatment*Measurement + random(Anemone_ID), data = pam_short_timeseries, family = GB1(), method = mixed(50:100), control = gamlss.control(n.cyc=200))

histDist(pam_short_timeseries$Fv_Fm_av, "GG", density = F, main = "generalised Gamma Lopatatsidis-Green")
histDist(pam_short_timeseries$Fv_Fm_av, "GB1", density = F, main = "GB1")

summary(pam_mod_full2)
```


# Base measurements

## Plots

```{r}
ggplot(base_clean, aes(fill = Treatment, x=Date, y = Average_Diameter)) + 
        theme_classic() +
         geom_boxplot() +
labs(x = "Date", Y = "Base diameter (mm)") +
  scale_fill_manual(values = c('#89226AFF',
                              '#2C728EFF',    
                              '#E65154FF')) +
  theme(axis.text=element_text(size=15),
        axis.title=element_text(size=20), 
        legend.text=element_text(size=15), 
        legend.title=element_text(size=20))
ggsave(path = "plots",filename = "base_boxplot.png", width = 10, height = 7)
```

## Testing distributions

```{r}
shapiro_test(base_clean$Average_Diameter)
#Data is non-normal

base_clean <- base_clean %>%
  mutate(log_diameter = log(Average_Diameter))
shapiro_test(base_clean$log_diameter)
#Log transformed data is normal

bartlett.test(log_diameter ~ Treatment, data = base_clean)
#Log transformed data has equal variances

base_clean %>%
  group_by(Date, Treatment) %>%
  identify_outliers(log_diameter)
#One extreme outlier
```

## ANOVA tests - delete later if not using

```{r}
base_aov <- anova_test(data = base_clean, dv = log_diameter, wid = Anemone_ID, within = c(Treatment, Date))

test_aov <- aov(log_diameter ~ Treatment*Date + Error(Anemone_ID/(Treatment*Date)), data=base_clean)

test_aov2<-ezANOVA(data = base_clean, dv = .(log_diameter), wid = .(Anemone_ID), within = c(Treatment, Date))

summary(test_aov)
table(base_clean$Treatment, base_clean$Date)
```

## Gamlss model

```{r}

fitDist(Average_Diameter, data = base_clean, type = "realAll", try.gamlss = T)
#Best fit: Box-Cox (LNO)

histDist(base_clean$Average_Diameter, "LNO", density = F, main = "Box-Cox")

base_mod_1 <- gamlss(Average_Diameter ~ Treatment + Date + Treatment*Date, data = base_clean, family = LNO())

base_mod_2 <- gamlss(log_diameter ~ Treatment + Date + Treatment*Date, data = base_clean, family = NO())

AIC(base_mod_1, base_mod_2)
#base_mod_2 (using the log-transformed data) has a lower AIC and therefore is a better fit for the data. 

summary(base_mod_2)
```

# Feeding time

## Plots

```{r}
#Line graph of feeding time
ggplot(data = food_summary, aes(x=Date, y = mean_time, group = Treatment, colour = Treatment)) + 
        theme_classic() +
         geom_point() +
        geom_line() +
        geom_errorbar(aes(ymin = mean_time- se_time, ymax = mean_time + se_time), width=0.2)

#Boxplot of feeding time
ggplot(food_clean, aes(fill = Treatment, x=Date, y = Feeding_Time_Min)) + 
        theme_classic() +
         geom_boxplot() +
  labs(x = "Date", Y = "Feeding time (min)") +
  scale_fill_manual(values = c('#89226AFF',
                              '#2C728EFF',    
                              '#E65154FF')) +
  theme(axis.text=element_text(size=15),
        axis.title=element_text(size=20), 
        legend.text=element_text(size=15), 
        legend.title=element_text(size=20))
ggsave(path = "plots",filename = "food_boxplot.png", width = 10, height = 7)
```

## Testing assumption

```{r}
shapiro.test(food_clean$Feeding_Time_Min)
#Data is non-normal

food_clean<-food_clean%>%
  mutate(log_Feeding_Time_Min = log(Feeding_Time_Min))
shapiro_test(food_clean$log_Feeding_Time_Min)
#Log transformed data fits normal distribution

bartlett.test(log_Feeding_Time_Min ~ Treatment, data = food_clean)
#Log transformed data has equal variances

food_clean %>%
  group_by(Date, Treatment) %>%
  identify_outliers(log_Feeding_Time_Min)
#Log transformed data has no extreme outliers
```

## ANOVA - delete if not using

```{r}
food_aov <- anova_test(data = food_clean, dv = log_Feeding_Time_Min, wid = Anemone_ID, within = c(Treatment, Date))


test <- gamlss(log_Feeding_Time_Min ~ Treatment*Date + random(Anemone_ID),  data = food_clean)
summary(test)
```


## Gamlss models
```{r}
fitDist(Feeding_Time_Min, data = food_clean, type = "realAll", try.gamlss = T)
#Best fit: Box-Cox (LNO)

histDist(food_clean$Feeding_Time_Min, "LNO", density = F, main = "Box-Cox")

food_mod_1 <- gamlss(Feeding_Time_Min ~ Treatment*Date + random(Anemone_ID), data = food_clean, family = LNO())

#Use test because no errors and better AIC
food_mod_2 <- gamlss(log_Feeding_Time_Min ~ Treatment*Date + random(Anemone_ID), data = food_clean, family = NO())

GAIC(food_mod_1, food_mod_2)
#food_mod_2 (using log-transformed data) has lower AIC and is therefore a better fit for the data.

summary(food_mod_2)

```

# Open/closed measurements

## Plots

```{r}
ggplot(data = open_closed_summary, aes(x = Time_Block, y = n, fill = Open_Closed)) + 
  geom_bar(position = "fill", stat = "identity") + 
  facet_grid(Date ~ Treatment) +
  labs(x="Time (hours)", y = "Proportion") +
  theme_classic()+
scale_fill_manual(values = c('#89226AFF',
                              '#2C728EFF',    
                              '#E65154FF')) 
ggsave(path = "plots",filename = "open_closed_plot.png", width = 10, height = 7)
```

## Exploratory data analysis

```{r}
#Summarizing the data
summary(open_closed_summary)
#Making frequency table
table(open_closed_summary$Treatment, open_closed_summary$Open_Closed)

```


## Giant Green Ordinal Model

```{r}
gg_model = clmm(Open_Closed ~ Treatment:Time_Block + (1|Anemone_ID), data = open_closed_clean)
summary(gg_model)


ord_model = clmm(Open_Closed ~ Treatment:Time_Block:Date + (1|Anemone_ID), data = open_closed_clean)
summary(ord_model)

```
